name: Deploy Go Gym API to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          docker build -t asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/go-gym/api:latest .
          docker push asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/go-gym/api:latest

      - name: Deploy to cloud run
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud run deploy go-gym-api \
            --image=asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/go-gym/api:latest \
            --platform=managed \
            --region=asia-southeast2 \
            --allow-unauthenticated
            --verbosity=debug
